### ISSUE TITLE
怎么进后台求教？

### ISSUE THREAD

**Issue by Sincejunly** [super-tongyao/wall#1]
![image](https://user-images.githubusercontent.com/96775034/226574291-c9de0284-3eda-4546-ab5a-704252057503.png)
![image](https://user-images.githubusercontent.com/96775034/226574456-2242d617-bec2-4b51-a4ad-4e7ce6dfe056.png)
Windows端，后台无法登录，用sql脚本创的数据库

**Comment by Sincejunly** [comment]
密码123456也不行

**Comment by Sincejunly** [comment]
没有防火墙，myqsl开的3306

**Comment by Sincejunly** [comment]
配置都改了，数据库用户名密码什么的，

**Comment by super-tongyao** [comment]
多少版本的？推荐下载最新的，贴一下登陆后台日志，密码是123456

**Comment by super-tongyao** [comment]
数据库有链接通吗？没有的话也是登陆不了的。

**Comment by Sincejunly** [comment]
> 数据库有链接通吗？没有的话也是登陆不了的。

日志在哪，数据库我不知道是否连通了，但是配置应该是对的

**Comment by Sincejunly** [comment]
![image](https://user-images.githubusercontent.com/96775034/226783468-c58ff55d-18a1-461a-9082-52462c84a310.png)

**Comment by Sincejunly** [comment]
> ![image](https://user-images.githubusercontent.com/96775034/226783468-c58ff55d-18a1-461a-9082-52462c84a310.png)

数据库有这个账户给了wall权限

**Comment by Sincejunly** [comment]
后端端口原来的9999也不行才改的

**Comment by Sincejunly** [comment]
> 多少版本的？推荐下载最新的，贴一下登陆后台日志，密码是123456

是最新的 昨天刚下的

**Comment by super-tongyao** [comment]
一般情况下，后端服务端口9999，因为在前端配置中，映射地址就是9999，其他没有问题，八成就是后端数据库配置、端口配置这些，如果默认情况下，只改数据库配置试试呢？数据库不知是否联通，这里得要确认下，可以在本地下个连接数据库的软件，测试一下

**Comment by super-tongyao** [comment]
还有你的数据库是在本机吗？

**Comment by Sincejunly** [comment]
> 还有你的数据库是在本机吗？

是的啊，数据库测试是通的，我用别的服务连上了

**Comment by Sincejunly** [comment]
> 一般情况下，后端服务端口9999，因为在前端配置中，映射地址就是9999，其他没有问题，八成就是后端数据库配置、端口配置这些，如果默认情况下，只改数据库配置试试呢？数据库不知是否联通，这里得要确认下，可以在本地下个连接数据库的软件，测试一下

日志在哪里 我看看 我现在也没有数据库软件，不太方便弄这个，可以的话你发个网址我去下

**Comment by Sincejunly** [comment]
发破解版的（
）

**Comment by super-tongyao** [comment]
日志查看
![1679456078168](https://user-images.githubusercontent.com/58587822/226795961-6150ed26-4c84-4ffc-b8bf-6393dcf4e59a.jpg)

**Comment by super-tongyao** [comment]
这类问题属于 小白新手 问题，相关资料请查阅百度。

**Comment by Sincejunly** [comment]
> 日志查看 ![1679456078168](https://user-images.githubusercontent.com/58587822/226795961-6150ed26-4c84-4ffc-b8bf-6393dcf4e59a.jpg)

![image](https://user-images.githubusercontent.com/96775034/226861704-35d10a06-2005-4bfd-b872-861b272c3781.png)
问题在于我所有的配置都是没问题的

**Comment by Sincejunly** [comment]
> 这类问题属于 小白新手 问题，相关资料请查阅百度。

你硬要说我配置错了我也没什么办法

**Comment by Sincejunly** [comment]
> 这类问题属于 小白新手 问题，相关资料请查阅百度。

![image](https://user-images.githubusercontent.com/96775034/226867095-40a7f65f-4722-45d1-9a84-6902ef90041d.png)

**Comment by Sincejunly** [comment]
![image](https://user-images.githubusercontent.com/96775034/226868851-ec58f03e-2cab-4fff-b69b-5e9618fbaaef.png)

**Comment by Sincejunly** [comment]
![image](https://user-images.githubusercontent.com/96775034/226868851-ec58f03e-2cab-4fff-b69b-5e9618fbaaef.png)
